import type { Supplier, SupplierStatus, AbcClass, EsgAnalysisProgress, EsgRiskStatus, CertificateState } from "./suppliers-model";

type MockSupplier = Omit<Supplier, "certificates" | "reach" | "rohs" | "esg" | "ownBusinessArea" | "publicIncidents"> & {
    certificates?: Partial<Supplier["certificates"]>;
    reach?: Partial<Supplier["reach"]>;
    rohs?: Partial<Supplier["rohs"]>;
    esg?: Partial<Supplier["esg"]>;
    ownBusinessArea?: Partial<Supplier["ownBusinessArea"]>;
    publicIncidents?: Supplier["publicIncidents"];
};

const NON_EXISTENT: CertificateState = "Non-existent";
const EXISTENT: CertificateState = "Existent";

function build(p: MockSupplier): Supplier {
    const {
        certificates,
        reach,
        rohs,
        esg,
        ownBusinessArea,
        publicIncidents,
        ...rest
    } = p;
    return {
        ...rest,
        certificates: {
            iso9001: NON_EXISTENT,
            iso13485: NON_EXISTENT,
            iso45001: NON_EXISTENT,
            iso17025: NON_EXISTENT,
            codeOfConduct: NON_EXISTENT,
            nda: NON_EXISTENT,
            iso14001: NON_EXISTENT,
            ...certificates,
        } as Supplier["certificates"],
        reach: { relevance: false, affected: "", notes: "", supplierSpecificNote: "", ...reach } as Supplier["reach"],
        rohs: { relevance: false, affected: "", note: "", supplierSpecificNote: "", ...rohs } as Supplier["rohs"],
        esg: {
            analysisProgress: "Waiting for SSA" as EsgAnalysisProgress,
            riskStatus: "Unknown" as EsgRiskStatus,
            riskStatusLast: "Unknown" as EsgRiskStatus,
            concreteRisk: "",
            humanRights: "",
            workersRights: "",
            environmental: "",
            existingKnowledge: "",
            ...esg,
        } as Supplier["esg"],
        ownBusinessArea: {
            analysisProgress: "",
            riskStatus: "",
            implementation1: "",
            implementation2: "",
            implementation3: "",
            contactPerson: "",
            ...ownBusinessArea,
        } as Supplier["ownBusinessArea"],
        publicIncidents: publicIncidents ?? [],
    };
}

const status = (s: SupplierStatus) => s;
const abc = (a: AbcClass) => a;

export const MOCK_SUPPLIERS: Supplier[] = [
    // ---- Active, fully onboarded, non-internal, high spend (views 1.1/5.1/2.3) ----
    build({
        id: "702478",
        name: "Helios Präzisionsteile GmbH",
        country: "DE",
        isicCode: "2599",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Mareike Brandt",
        supplierType: "Manufacturer",
        areaOfNeed: ["Production", "Tooling"],
        commodityGroup: "Machined Components",
        strategicClassification: "Preferred Supplier (P)",
        abcClassification: abc("A"),
        orderVolume2025: 4_820_000,
        orderVolume2024: 4_150_000,
        supplierSpend: 4_820_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        certificates: { iso9001: EXISTENT, codeOfConduct: EXISTENT, nda: EXISTENT },
        reach: { relevance: true, affected: "SVHC candidate list < 0.1%", notes: "Declared", supplierSpecificNote: "No article-level risk" },
        rohs: { relevance: true, affected: "Compliant", note: "RoHS 3", supplierSpecificNote: "No exemptions used" },
        esg: {
            analysisProgress: "Completed",
            riskStatus: "Low risk",
            riskStatusLast: "Low risk",
            concreteRisk: "None identified",
            humanRights: "Audited",
            workersRights: "Audited",
            environmental: "ISO 50001 planned",
            existingKnowledge: "2 prior assessments",
        },
    }),
    build({
        id: "702491",
        name: "Nordpol Stahl AG",
        country: "DE",
        isicCode: "2410",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Tobias Keller",
        supplierType: "Manufacturer",
        areaOfNeed: ["Production"],
        commodityGroup: "Raw Steel",
        strategicClassification: "Strategic Supplier (S)",
        abcClassification: abc("A"),
        orderVolume2025: 6_150_000,
        orderVolume2024: 5_900_000,
        supplierSpend: 6_150_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        certificates: { iso9001: EXISTENT, iso14001: EXISTENT, codeOfConduct: EXISTENT },
        reach: { relevance: true, affected: "Substance declared", notes: "In progress", supplierSpecificNote: "" },
        rohs: { relevance: true, affected: "Compliant", note: "RoHS 3", supplierSpecificNote: "" },
        esg: {
            analysisProgress: "Completed",
            riskStatus: "Medium risk",
            riskStatusLast: "High risk",
            concreteRisk: "Scope 3 emissions gap",
            humanRights: "Partial",
            workersRights: "Audited",
            environmental: "Needs improvement",
            existingKnowledge: "1 prior assessment",
        },
    }),
    build({
        id: "702503",
        name: "Bavaria Kunststoffe e.K.",
        country: "DE",
        isicCode: "2229",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Mareike Brandt",
        supplierType: "Manufacturer",
        areaOfNeed: ["Production", "R&D"],
        commodityGroup: "Injection Molding",
        strategicClassification: "Preferred Supplier (P)",
        abcClassification: abc("B"),
        orderVolume2025: 1_240_000,
        orderVolume2024: 980_000,
        supplierSpend: 1_240_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        certificates: { iso9001: EXISTENT },
        reach: { relevance: true, affected: "SVHC < 0.1%", notes: "Declared", supplierSpecificNote: "" },
        rohs: { relevance: false },
        esg: {
            analysisProgress: "In progress",
            riskStatus: "Medium risk",
            riskStatusLast: "Medium risk",
            concreteRisk: "Chemical handling",
            humanRights: "Partial",
            workersRights: "Partial",
            environmental: "Under review",
            existingKnowledge: "Self-reported",
        },
    }),
    build({
        id: "702517",
        name: "RheinMetal Components",
        country: "DE",
        isicCode: "2599",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Tobias Keller",
        supplierType: "Manufacturer",
        areaOfNeed: ["Production"],
        commodityGroup: "Forgings",
        strategicClassification: "Strategic Supplier (S)",
        abcClassification: abc("B"),
        orderVolume2025: 2_300_000,
        orderVolume2024: 2_100_000,
        supplierSpend: 2_300_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        certificates: { iso9001: EXISTENT, iso45001: EXISTENT, codeOfConduct: EXISTENT, nda: EXISTENT },
        reach: { relevance: true, affected: "Declared", notes: "Declared", supplierSpecificNote: "" },
        rohs: { relevance: true, affected: "Compliant", note: "RoHS 3", supplierSpecificNote: "" },
        esg: {
            analysisProgress: "Completed",
            riskStatus: "Low risk",
            riskStatusLast: "Low risk",
            concreteRisk: "None",
            humanRights: "Audited",
            workersRights: "Audited",
            environmental: "ISO 14001",
            existingKnowledge: "3 prior assessments",
        },
    }),
    // ---- Internal / own business area (5.4) ----
    build({
        id: "700112",
        name: "Prettl Werkzeugbau (Internal)",
        country: "DE",
        isicCode: "2573",
        internal: true,
        supplierStatus: status("Active"),
        responsibleBuyer: "Internal Plant",
        commodityGroup: "Tooling",
        strategicClassification: "Internal (I)",
        abcClassification: abc("C"),
        orderVolume2025: 320_000,
        orderVolume2024: 300_000,
        supplierSpend: 320_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        certificates: { iso9001: EXISTENT },
        reach: { relevance: false },
        rohs: { relevance: false },
        esg: {
            analysisProgress: "Completed",
            riskStatus: "Low risk",
            riskStatusLast: "Low risk",
            concreteRisk: "N/A",
            humanRights: "Internal policy",
            workersRights: "Internal policy",
            environmental: "Internal policy",
            existingKnowledge: "Internal",
        },
        ownBusinessArea: {
            analysisProgress: "Completed",
            riskStatus: "Low risk",
            implementation1: "Energy audit done",
            implementation2: "Waste segregation",
            implementation3: "Training rolled out",
            contactPerson: "Lena Prettl",
        },
    }),
    build({
        id: "700118",
        name: "Prettl Elektronik (Internal)",
        country: "DE",
        isicCode: "2611",
        internal: true,
        supplierStatus: status("Active"),
        responsibleBuyer: "Internal Plant",
        commodityGroup: "PCBA",
        strategicClassification: "Internal (I)",
        abcClassification: abc("C"),
        orderVolume2025: 540_000,
        orderVolume2024: 510_000,
        supplierSpend: 540_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        ownBusinessArea: {
            analysisProgress: "In progress",
            riskStatus: "Medium risk",
            implementation1: "Conflict minerals check",
            implementation2: "",
            implementation3: "Pending",
            contactPerson: "Jonas Prettl",
        },
        esg: {
            analysisProgress: "In progress",
            riskStatus: "Medium risk",
            riskStatusLast: "Unknown",
            concreteRisk: "Tantalum sourcing",
            humanRights: "Partial",
            workersRights: "Partial",
            environmental: "Review",
            existingKnowledge: "Internal",
        },
    }),
    // ---- Potential suppliers (2.1) — count 3 ----
    build({
        id: "703901",
        name: "Shenzhen Lumen Optics",
        country: "CN",
        isicCode: "2670",
        internal: false,
        supplierStatus: status("Potential Supplier"),
        responsibleBuyer: "Aiko Tanaka",
        supplierType: "Manufacturer",
        areaOfNeed: ["Production"],
        commodityGroup: "Optics",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: true,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
        reach: { relevance: true, affected: "Pending declaration", notes: "", supplierSpecificNote: "" },
    }),
    build({
        id: "703904",
        name: "Pune Precision Ltd.",
        country: "IN",
        isicCode: "2599",
        internal: false,
        supplierStatus: status("Potential Supplier"),
        responsibleBuyer: "Ravi Menon",
        supplierType: "Manufacturer",
        areaOfNeed: ["Production", "Logistics"],
        commodityGroup: "Turned Parts",
        strategicClassification: "",
        abcClassification: abc("B"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: true,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
    build({
        id: "703907",
        name: "Guadalajara Cables S.A.",
        country: "MX",
        isicCode: "2732",
        internal: false,
        supplierStatus: status("Potential Supplier"),
        responsibleBuyer: "Aiko Tanaka",
        commodityGroup: "Harness",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: false,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
    // ---- In qualification (2.2) ----
    build({
        id: "702650",
        name: "Torino Stampi S.r.l.",
        country: "IT",
        isicCode: "2573",
        internal: false,
        supplierStatus: status("Evaluation Process"),
        responsibleBuyer: "Marco Rossi",
        commodityGroup: "Tooling",
        strategicClassification: "",
        abcClassification: abc("B"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: false,
        supplierCreatedIn: false,
        certificates: { iso9001: EXISTENT },
        esg: {
            analysisProgress: "Waiting for SSA",
            riskStatus: "Unknown",
            riskStatusLast: "Unknown",
            concreteRisk: "",
            humanRights: "",
            workersRights: "",
            environmental: "",
            existingKnowledge: "",
        },
    }),
    build({
        id: "702661",
        name: "Kraków Formy Sp. z o.o.",
        country: "PL",
        isicCode: "2573",
        internal: false,
        supplierStatus: status("Evaluation Process"),
        responsibleBuyer: "Marco Rossi",
        commodityGroup: "Tooling",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
    // ---- Rejected (2.4) ----
    build({
        id: "703002",
        name: "Hanoi Fasteners Co.",
        country: "VN",
        isicCode: "2593",
        internal: false,
        supplierStatus: status("Rejected Supplier"),
        responsibleBuyer: "Ravi Menon",
        commodityGroup: "Fasteners",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: true,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
    // ---- High-risk suspicious (4.2) + REACH/RoHS ----
    build({
        id: "704211",
        name: "Yangon Textiles Ltd.",
        country: "CN",
        isicCode: "1392",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Aiko Tanaka",
        commodityGroup: "Textiles",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 780_000,
        orderVolume2024: 650_000,
        supplierSpend: 780_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        reach: { relevance: true, affected: "Substance under review", notes: "Open", supplierSpecificNote: "Awaiting data" },
        rohs: { relevance: true, affected: "Non-compliant lot flagged", note: "RoHS 3", supplierSpecificNote: "Investigation" },
        esg: {
            analysisProgress: "Completed",
            riskStatus: "High risk",
            riskStatusLast: "Medium risk",
            concreteRisk: "Forced labor allegation",
            humanRights: "Critical gaps",
            workersRights: "Critical gaps",
            environmental: "Pollution incident",
            existingKnowledge: "NGO report",
        },
        publicIncidents: [
            { status: "Violation confirmed", category: "Labor", briefJustification: "Local audit confirmed wage violations", sources: "Labor Watch 2025" },
        ],
    }),
    build({
        id: "704220",
        name: "Manaus Components",
        country: "BR",
        isicCode: "2732",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Marco Rossi",
        commodityGroup: "Harness",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 410_000,
        orderVolume2024: 360_000,
        supplierSpend: 410_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        reach: { relevance: false },
        rohs: { relevance: true, affected: "Compliant", note: "RoHS 3", supplierSpecificNote: "" },
        esg: {
            analysisProgress: "Completed",
            riskStatus: "Medium risk",
            riskStatusLast: "High risk",
            concreteRisk: "Deforestation linkage",
            humanRights: "Partial",
            workersRights: "Partial",
            environmental: "High concern",
            existingKnowledge: "Satellite data",
        },
        publicIncidents: [
            { status: "Potential discrepancy", category: "Environmental", briefJustification: "Unverified claim of illegal logging", sources: "Local press" },
        ],
    }),
    // ---- Waiting for SSA (5.3) ----
    build({
        id: "705300",
        name: "Lyon Connecteurs",
        country: "FR",
        isicCode: "2733",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Marco Rossi",
        commodityGroup: "Connectors",
        strategicClassification: "Preferred Supplier (P)",
        abcClassification: abc("B"),
        orderVolume2025: 620_000,
        orderVolume2024: 540_000,
        supplierSpend: 620_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: false,
        supplierCreatedIn: true,
        esg: {
            analysisProgress: "Waiting for SSA",
            riskStatus: "Unknown",
            riskStatusLast: "Unknown",
            concreteRisk: "",
            humanRights: "",
            workersRights: "",
            environmental: "",
            existingKnowledge: "",
        },
    }),
    // ---- Low spend, internal blank (drives 5.1 but excluded by spend) ----
    build({
        id: "705311",
        name: "Oslo Polymer AS",
        country: "FR",
        isicCode: "2229",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Mareike Brandt",
        commodityGroup: "Polymers",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 3_200,
        orderVolume2024: 2_900,
        supplierSpend: 3_200,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        esg: {
            analysisProgress: "In progress",
            riskStatus: "Low risk",
            riskStatusLast: "Low risk",
            concreteRisk: "None",
            humanRights: "Audited",
            workersRights: "Audited",
            environmental: "Good",
            existingKnowledge: "1 assessment",
        },
    }),
    // ---- test Lieferant PMA (id matches detail page seed) ----
    build({
        id: "PMA-9001",
        name: "test Lieferant PMA",
        country: "DE",
        isicCode: "2599",
        internal: false,
        supplierStatus: status("Active"),
        responsibleBuyer: "Anna Müller",
        supplierType: "Manufacturer",
        areaOfNeed: ["Direct", "Production"],
        commodityGroup: "Precision Machined Parts",
        strategicClassification: "Preferred Supplier (P)",
        abcClassification: abc("A"),
        orderVolume2025: 4_280_000,
        orderVolume2024: 3_950_000,
        supplierSpend: 4_280_000,
        ssaSent: true,
        ssaReceived: true,
        ssaCompleted: true,
        supplierCreatedIn: true,
        certificates: { iso9001: EXISTENT, codeOfConduct: EXISTENT, nda: EXISTENT },
    }),
    // ---- Sparse placeholders so list view shows multiple rows ----
    build({
        id: "TEST123",
        name: "TEST123",
        country: "DE",
        isicCode: "",
        internal: false,
        supplierStatus: status("Potential Supplier"),
        responsibleBuyer: "",
        commodityGroup: "",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: false,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
    build({
        id: "ASQ-1042",
        name: "ASQtec GmbH",
        country: "DE",
        isicCode: "",
        internal: false,
        supplierStatus: status("Evaluation Process"),
        responsibleBuyer: "",
        commodityGroup: "",
        strategicClassification: "",
        abcClassification: abc("B"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: false,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
    build({
        id: "WHA-2208",
        name: "W.H. Augenstein",
        country: "DE",
        isicCode: "",
        internal: false,
        supplierStatus: status("Potential Supplier"),
        responsibleBuyer: "",
        commodityGroup: "",
        strategicClassification: "",
        abcClassification: abc("C"),
        orderVolume2025: 0,
        orderVolume2024: 0,
        supplierSpend: 0,
        ssaSent: false,
        ssaReceived: false,
        ssaCompleted: false,
        supplierCreatedIn: false,
    }),
];
