// Seed dataset for the "test Lieferant PMA" supplier.
// All other suppliers render mostly empty per current screenshots.

export interface PmaSeedData {
    overview: {
        aiSummary: string;
        transactionVolume: { year: number; volume: number }[];
        categoryVolume: { category: string; share: number }[];
    };
    properties: Record<string, unknown>;
    tables: {
        investmentVolume: Array<Record<string, unknown>>;
        annualRevenue: Array<Record<string, unknown>>;
        numberOfEmployees: Array<Record<string, unknown>>;
        sites: Array<Record<string, unknown>>;
    };
    certificates: Record<string, "Accepted" | "Non-existent" | string | undefined>;
}

export const PMA_SUPPLIER_ID = "PMA-TEST-001";
export const PMA_SUPPLIER_NAME = "test Lieferant PMA";

const pmaProperties: Record<string, unknown> = {
    // Supplier profile
    supplier_number: "PMA-9001",
    company_name: "test Lieferant PMA",
    address: "Allmandstraße 9, 72290 Lossburg-Betzweiler, Germany",
    public_website: "www.prettl.com",
    bank_name: "Dagobert Dug Investments Inc.",
    iban: "GB33BUKB20201555555555",
    bic_swift: "123",
    account_currency: "USD",

    // Legal
    legal_form: "GmbH",
    parent_company: "PMA Holding SE",
    tax_number: "DE 123 456 789",
    vat_id: "123",
    year_founded: 1998,

    // User defined
    order_volume_2025: 4_280_000,
    order_volume_2024: 3_950_000,
    responsible_buyer: "Anna Müller",
    abc_classification: "A",
    supplier_status: "Potential Supplier",
    area_of_need: ["Direct"],
    supplier_type: "Manufacturer",
    commodity_group: "Precision Machined Parts",
    strategic_classification: "Preferred Supplier (P)",
    ssa_sent: "Sent",
    ssa_reviewed: "Reviewed",
    rfq_package_approved: true,
    rfq_package_sent_out: true,
    onboarding_audit_conducted: true,
    onboarding_audit: "Passed",
    ssa_completed: "Yes",
    transfer_supplier_number_to_tacto: true,
    supplier_created_in_erp: true,
    rohs_note: "Compliant per supplier declaration 2024",
    rohs_affected: "No",
    supplier_spend: 4_280_000,
    rohs_relevance: "Yes",
    reach_relevance: "Yes",
    reach_notes: "SVHC declaration provided 2024-12",
    reach_affected: "No",
    core_competences:
        "Stamping",
    main_equipment:
        "CNC machine, Moulding machine",
    annual_purchase_volume_main_suppliers:
        "TE, 30%\nLeoni, 25%\nTele-Fonika, 18%\nLumberg, 14%\nSchwager, 12%",
    turnover_share: 100,
    consignation_stock_possible: "Yes",
    customers_80_sales: 4,
    customer_audits:
        "Kd C, Herbstaudit, 01.10.2025, tiptop\nKd B, Sommeraudit, 10.07.2025, geht so\nKd A, Frühjahrsaudit, 12.03.2025, guter Kaffee",
    main_customers_share:
        "Fa XL, 50%\nFa L, 15%\nFa M, 10%\nFa S, 5%",
    number_of_customers: 100,

    employees_engineers: 0,
    employees_management: 1,
    employees_direct: 80,
    employees_indirect: 39,
    employees_total_prev: 100,
    employees_total_current: 120,

    // Production site & contacts (key roles)
    contact_order_phone: "+49 711 12345-10",
    contact_order_email: "order@pma-test.example",
    contact_order_name_planned_site: "Klaus Becker",
    contact_emergency_phone: "+49 711 12345-99",
    contact_emergency_email: "emergency@pma-test.example",
    contact_emergency_name_planned_site: "24/7 Hotline",
    contact_purchasing_phone: "+49 711 12345-30",
    contact_purchasing_email: "purchasing@pma-test.example",
    contact_purchasing_name_planned_site: "Anna Müller",
    contact_quality_phone: "+49 711 12345-50",
    contact_quality_email: "quality@pma-test.example",
    contact_quality_name_planned_site: "Stefan Klein",
    contact_sales_phone: "+49 711 12345-20",
    contact_sales_email: "sales@pma-test.example",
    contact_sales_name_planned_site: "Markus Wagner",
    contact_ceo_name_planned_site: "Dr. Heinrich Schäfer",
    production_site_contact_phone: "123",
    production_site_contact_email: "torsten.vorwerk@pas-net.com",
    production_site_contact_name: "Meister Lampe",
    production_site_country: "Deutschland",
    production_site_area_m2: 3,
    production_site_postal_city: "16816 Neuruppin",
    production_site_company_name: "PAS Cable GmbH",
    insurance_no: "123",
    amount_insured: 200,
    location_headquarter: "Neuruppin",
    local_trade_register: "HRB1111",
    insurer: "ALLIANZ AG",
    duns_no: "456",
    year_established: 1998,
    eori_no: "123",

    // ESG / LkSG
    esg_internal: false,
    esg_risk_status: "Low risk",
    esg_country_code: "DE",
    esg_isic_code: "2599",
    esg_analysis_progress: "Completed",
    esg_categories: "Automotive, Industrial",
    esg_environmental_score: 78,
    esg_human_score: 82,
    esg_workers_score: 80,
    esg_concrete_risk_score: 12,
    esg_human_self_assessment: "Yes",
    esg_environmental_self_assessment: "Yes",
    esg_workers_self_assessment: "Yes",
    esg_reporting_organisation: "PAS Cable GmbH",
    esg_implementation_environmental: "Implemented",
    esg_implementation_human: "Implemented",
    esg_implementation_labor: "Implemented",
    esg_risk_status_egb: "Low risk",
    esg_analysis_progress_egb: "Completed",
    esg_reporting_obligation: "Yes",
    esg_contact_person: "Anna Müller",
    esg_risk_assessment_labor: "Low",
    esg_reasoning_labor:
        "No reported violations in own business area. Strong compliance program documented.",
    esg_risk_assessment_human: "Low",
    esg_reasoning_human:
        "Self-assessment completed, all rights covered. Annual training in place.",
    esg_risk_assessment_environmental: "Low",
    esg_reasoning_environmental:
        "ISO 14001 certified, environmental KPIs monitored, no critical findings in last audit.",

    // LP factors
    lp_1_appropriateness_causation: "Low",
    lp_1_influence_1: "Low",
    lp_1_severity: "Low",
    lp_1_likelihood: "Low",
    lp_2_appropriateness_causation: "Low",
    lp_2_influence_1: "Low",
    lp_2_severity: "Low",
    lp_2_likelihood: "Low",
    lp_3_appropriateness_causation: "Low",
    lp_3_influence_1: "Low",
    lp_3_severity: "Low",
    lp_3_likelihood: "Low",

    esg_human_score_final: 82,
    esg_environmental_score_final: 78,
    esg_workers_score_final: 80,
    esg_score_mitigation: 85,
    esg_industry_score: 75,
    esg_country_score: 90,
    esg_appropriateness_1: 0.8,
    esg_appropriateness_2: 0.8,
    esg_appropriateness_3: 0.8,
    esg_risk_analysis_skipped_comment: "",
    esg_skip_risk_analysis: "No",
    esg_risk_analysis_doc: "",
    esg_attachment_dropzone: "",
    esg_comment: "No findings; routine monitoring.",
    esg_risk_status_workers: "Low risk",
    esg_risk_status_human: "Low risk",
    esg_risk_status_environmental: "Low risk",

    // LkSG clauses (excerpt)
    lksg_3_1: "Annual risk analysis conducted",
    lksg_3_2: "No known violations",
    lksg_4_1: "Compliance officer designated",
    lksg_4_2: "",
    lksg_4_3: "No",
    lksg_5_1: "01.01.2024 – 31.12.2024",
    lksg_5_2: "Media screening, supplier self-assessment, on-site audits",
    lksg_5_3: "Internal hotline + external whistleblower platform",
    lksg_5_4: "Annual SSA + spot-check audits",
    lksg_5_5: "Risk-based desk research",
    lksg_6_1: "Cable manufacturing, stamping",
    lksg_7_1_1: "PAS Cable GmbH",
    lksg_7_1_2: "Yes",
    lksg_7_1_1_no: "Yes",
    lksg_7_1_3: "Neuruppin, Germany",
    lksg_7_1_4: "Germany",
    lksg_7_1_5: "Manufacturing",
    lksg_7_1_6: "Production",
    lksg_8_1: "DE",
    lksg_8_2: 48,
    lksg_8_3: "Copper wire, raw cable materials, stamping tools",
    lksg_8_4: "Copper, Steel",
    lksg_percentage_ownership: 100,
    lksg_information_auditability: "On-site audits performed on 6 of top 10 suppliers",
    lksg_bafa_report: "Submitted",
    lksg_strategic_buyer: "Anna Müller",
    lksg_statement_violations: "No known violations",
    lksg_informant: "",
    lksg_abstract_risk_score: 18,
    lksg_comment_subsidiary_type: "Operating subsidiary",
    lksg_address_affiliate: "Allmandstraße 9, 72290 Lossburg-Betzweiler",
    lksg_country_subsidiary: "DE",
    lksg_subsidiary_type: "Producing",
    lksg_affiliation_corporate_group: "Yes",
    lksg_legal_form: "GmbH",
    lksg_comment_affiliation: "Fully owned operating subsidiary",
    lksg_employees_egb: 120,
    lksg_role_contact: "Compliance Officer",
    lksg_email_contact: "torsten.vorwerk@pas-net.com",
    lksg_website_affiliate: "www.prettl.com",
    lksg_industry_egb: "Manufacturing",
    lksg_products_egb: "Cables, Stamping",
    lksg_significance_affiliate: "High",
    lksg_annual_revenue_previous: 60_000_000,
    lksg_supply_chain_egb: "Tier-1 + Tier-2 monitored",
    lksg_procurement_focus_egb: "Long-term partnerships with EU suppliers",
    lksg_labor_violation: "No",
    lksg_environmental_violation: "No",
    lksg_human_violation: "No",
    lksg_internal_note: "All clear",
    lksg_category: "Human Rights",
    lksg_captured_on: "2024-12-15",
    lksg_sources: "Internal audit, supplier self-assessment",
    lksg_existing_knowledge: "Existing knowledge",
    lksg_brief_justification: "No findings, all controls in place",
    lksg_status: "Cleared",
    lksg_assigned_violation: "None",
    lksg_emas: "Non-existent",
    lksg_emas_requested: "Non-existent",
    lksg_iso_37001: "Non-existent",
    lksg_iso_37001_requested: "Non-existent",

    // LkSG LP topic answers (sample, all "No"/"Effective" for low-risk supplier)
    lksg_lp_1_q_forced_labor_process_2025_wahl: "No",
    lp_1_q_forced_labor: "No",
    lp_1_forced_labor_1: "No",
    lp_1_forced_labor_2: "",
    lp_1_forced_labor_3: "Yes",
    lp_1_forced_labor_4: "Recruitment policy prohibits fees",
    lp_1_forced_labor_5: "Effective",
    lp_1_forced_labor_6: "Audited annually, no findings",
};

const pmaCertificates: Record<string, "Accepted" | "Non-existent" | string | undefined> = {
    iso_9001: "13.08.2026",
    iso_14001: "28.08.2026",
    iso_13485: "28.08.2026",
    iso_50001: "28.08.2026",
    iso_45001: "28.08.2026",
    ohsas_18001: "Non-existent",
    din_en_iso_3834_2: "Non-existent",
    ad_2000_wx: "Non-existent",
    din_en_1090_2: "Non-existent",
    iso_9000: "Non-existent",
    iso_27001: "Non-existent",
    iso_iec_80079_34: "Non-existent",
    en_as_9100: "Non-existent",
    kat: "Non-existent",
    brc: "Non-existent",
    fssc: "Non-existent",
    vda_6_1: "Non-existent",
    haccp: "Non-existent",
    iso_iec_27001: "Non-existent",
    mmog: "Non-existent",
    ifs: "Non-existent",
    sedex_smeta: "Non-existent",
    halal: "Non-existent",
    kosher: "Non-existent",
    iso_26000: "Non-existent",
    icti_ietp: "Non-existent",
    amfori_bsci: "Non-existent",
    sa_8000: "Non-existent",
    tisax: "Non-existent",
    din_en_1090_3: "Non-existent",
    din_en_iso_3834: "Non-existent",
    iso_17025: "Non-existent",
    agb: "Accepted",
    entsorgung: "Non-existent",
    langzeit: "Accepted",
    qsv: "Accepted",
    rahmenvertrag: "Accepted",
    reach: "Accepted",
    rohs: "Accepted",
    verhaltenskodex: "Valid",
    verhaltenskodex_requested: "Accepted",
    nda: "Accepted",
    iatf_16949: "31.12.2028",
    iso_37001: "Non-existent",
    emas: "Non-existent",
};

const pmaTables: PmaSeedData["tables"] = {
    investmentVolume: [
        { year: 2024, investment_volume: 1_200_000 },
        { year: 2023, investment_volume: 950_000 },
    ],
    annualRevenue: [
        { year: 2026, revenue: 56_000_000 },
        { year: 2025, revenue: 60_000_000 },
        { year: 2024, revenue: 40_000_000 },
    ],
    numberOfEmployees: [
        { year: 2024, all: 120, rnd: 0, sales: 1, quality: 0, production: 80 },
        { year: 2023, all: 100, rnd: 0, sales: 1, quality: 0, production: 80 },
    ],
    sites: [
        { description: "abcd", divisions: "PRODUCTION", working_shifts: 2 },
    ],
};

const pmaOverview: PmaSeedData["overview"] = {
    aiSummary:
        "Potential Supplier based in Lossburg-Betzweiler (parent group: Prettl). Manufacturing focus on stamping and cable production. ISO 9001/14001/45001/50001/13485/IATF 16949 certifications valid. Recommended for onboarding review.",
    transactionVolume: [
        { year: 2026, volume: 2_800_000 },
        { year: 2025, volume: 3_100_000 },
        { year: 2024, volume: 3_400_000 },
        { year: 2023, volume: 3_950_000 },
        { year: 2022, volume: 4_150_000 },
    ],
    categoryVolume: [
        { category: "Stamping", share: 50 },
        { category: "Cables", share: 30 },
        { category: "Other", share: 20 },
    ],
};

export const PMA_SEED: PmaSeedData = {
    overview: pmaOverview,
    properties: pmaProperties,
    tables: pmaTables,
    certificates: pmaCertificates,
};
